apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga-front
  template:
    metadata:
      labels:
        app: taiga-front
    spec:
      restartPolicy: Always
      containers:
        - name: taiga-front
          image: taigaio/taiga-front:latest
          ports:
            - containerPort: 80
          env:
            - name: TAIGA_URL
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: TAIGA_URL
            - name: TAIGA_WEBSOCKETS_URL
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: TAIGA_WEBSOCKETS_URL
            - name: TAIGA_SUBPATH
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: TAIGA_SUBPATH
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '512Mi'
              cpu: '400m'
