apiVersion: v1
kind: Service
metadata:
  name: taiga-back
  namespace: taiga
spec:
  selector:
    app: taiga-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-db
  namespace: taiga
spec:
  selector:
    app: taiga-db
  ports:
    - protocol: TCP
      port: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-front
  namespace: taiga
spec:
  selector:
    app: taiga-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-async
  namespace: taiga
spec:
  selector:
    app: taiga-async
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-async-rabbitmq
  namespace: taiga
spec:
  selector:
    app: taiga-async-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: rabbitmq
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: rabbitmq-management

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-events-rabbitmq
  namespace: taiga
spec:
  selector:
    app: taiga-events-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: rabbitmq
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: rabbitmq-management

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-gateway
  namespace: taiga
spec:
  selector:
    app: taiga-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-protected
  namespace: taiga
spec:
  selector:
    app: taiga-protected
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-events
  namespace: taiga
spec:
  selector:
    app: taiga-events
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
